// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(resvg_swiftFFI)
import resvg_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_resvg_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_resvg_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A parsed SVG. Parsing is the expensive part — the XML, the CSS, the text
 * layout — so a host keeps this and asks it for a display list per draw.
 */
public protocol SvgDocumentProtocol : AnyObject {
    
    /**
     * The picture as a display list.
     *
     * `raster_scale` is device pixels per user unit for anything that has to be
     * rasterized (filters, masks, patterns): a 100-unit document drawn 300
     * points wide on a 2× display passes `6.0`. Vector ops are the same at
     * every scale.
     */
    func displayList(rasterScale: Float)  -> DisplayList
    
    /**
     * Whether the document has `<text>` — a host may want to know that fonts
     * mattered to what it is showing.
     */
    func hasText()  -> Bool
    
    /**
     * The document's height in user units.
     */
    func height()  -> Float
    
    /**
     * The document's width in user units — its `width` as usvg resolved it.
     */
    func width()  -> Float
    
}

/**
 * A parsed SVG. Parsing is the expensive part — the XML, the CSS, the text
 * layout — so a host keeps this and asks it for a display list per draw.
 */
open class SvgDocument:
    SvgDocumentProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_resvg_swift_fn_clone_svgdocument(self.pointer, $0) }
    }
    /**
     * Parse `data` — plain or gzip-compressed SVG.
     */
public convenience init(data: Data, options: ParseOptions)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeSvgError.lift) {
    uniffi_resvg_swift_fn_constructor_svgdocument_new(
        FfiConverterData.lower(data),
        FfiConverterTypeParseOptions.lower(options),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_resvg_swift_fn_free_svgdocument(pointer, $0) }
    }

    

    
    /**
     * The picture as a display list.
     *
     * `raster_scale` is device pixels per user unit for anything that has to be
     * rasterized (filters, masks, patterns): a 100-unit document drawn 300
     * points wide on a 2× display passes `6.0`. Vector ops are the same at
     * every scale.
     */
open func displayList(rasterScale: Float) -> DisplayList {
    return try!  FfiConverterTypeDisplayList.lift(try! rustCall() {
    uniffi_resvg_swift_fn_method_svgdocument_display_list(self.uniffiClonePointer(),
        FfiConverterFloat.lower(rasterScale),$0
    )
})
}
    
    /**
     * Whether the document has `<text>` — a host may want to know that fonts
     * mattered to what it is showing.
     */
open func hasText() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_resvg_swift_fn_method_svgdocument_has_text(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The document's height in user units.
     */
open func height() -> Float {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_resvg_swift_fn_method_svgdocument_height(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The document's width in user units — its `width` as usvg resolved it.
     */
open func width() -> Float {
    return try!  FfiConverterFloat.lift(try! rustCall() {
    uniffi_resvg_swift_fn_method_svgdocument_width(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSvgDocument: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SvgDocument

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SvgDocument {
        return SvgDocument(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SvgDocument) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SvgDocument {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SvgDocument, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSvgDocument_lift(_ pointer: UnsafeMutableRawPointer) throws -> SvgDocument {
    return try FfiConverterTypeSvgDocument.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSvgDocument_lower(_ value: SvgDocument) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSvgDocument.lower(value)
}


/**
 * One `clipPath`: the union of its shapes.
 */
public struct Clip {
    public var shapes: [ClipShape]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(shapes: [ClipShape]) {
        self.shapes = shapes
    }
}



extension Clip: Equatable, Hashable {
    public static func ==(lhs: Clip, rhs: Clip) -> Bool {
        if lhs.shapes != rhs.shapes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(shapes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClip: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Clip {
        return
            try Clip(
                shapes: FfiConverterSequenceTypeClipShape.read(from: &buf)
        )
    }

    public static func write(_ value: Clip, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeClipShape.write(value.shapes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClip_lift(_ buf: RustBuffer) throws -> Clip {
    return try FfiConverterTypeClip.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClip_lower(_ value: Clip) -> RustBuffer {
    return FfiConverterTypeClip.lower(value)
}


/**
 * One shape of a clip.
 */
public struct ClipShape {
    public var path: Path
    /**
     * Local to canvas.
     */
    public var transform: Transform
    public var rule: FillRule

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: Path, 
        /**
         * Local to canvas.
         */transform: Transform, rule: FillRule) {
        self.path = path
        self.transform = transform
        self.rule = rule
    }
}



extension ClipShape: Equatable, Hashable {
    public static func ==(lhs: ClipShape, rhs: ClipShape) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.rule != rhs.rule {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(transform)
        hasher.combine(rule)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClipShape: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClipShape {
        return
            try ClipShape(
                path: FfiConverterTypePath.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                rule: FfiConverterTypeFillRule.read(from: &buf)
        )
    }

    public static func write(_ value: ClipShape, into buf: inout [UInt8]) {
        FfiConverterTypePath.write(value.path, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterTypeFillRule.write(value.rule, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipShape_lift(_ buf: RustBuffer) throws -> ClipShape {
    return try FfiConverterTypeClipShape.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClipShape_lower(_ value: ClipShape) -> RustBuffer {
    return FfiConverterTypeClipShape.lower(value)
}


/**
 * An opaque sRGB colour. Opacity travels separately.
 */
public struct Color {
    public var red: UInt8
    public var green: UInt8
    public var blue: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(red: UInt8, green: UInt8, blue: UInt8) {
        self.red = red
        self.green = green
        self.blue = blue
    }
}



extension Color: Equatable, Hashable {
    public static func ==(lhs: Color, rhs: Color) -> Bool {
        if lhs.red != rhs.red {
            return false
        }
        if lhs.green != rhs.green {
            return false
        }
        if lhs.blue != rhs.blue {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(red)
        hasher.combine(green)
        hasher.combine(blue)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeColor: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Color {
        return
            try Color(
                red: FfiConverterUInt8.read(from: &buf), 
                green: FfiConverterUInt8.read(from: &buf), 
                blue: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: Color, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.red, into: &buf)
        FfiConverterUInt8.write(value.green, into: &buf)
        FfiConverterUInt8.write(value.blue, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColor_lift(_ buf: RustBuffer) throws -> Color {
    return try FfiConverterTypeColor.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeColor_lower(_ value: Color) -> RustBuffer {
    return FfiConverterTypeColor.lower(value)
}


/**
 * A dash pattern.
 */
public struct Dash {
    /**
     * On/off lengths. Even in length and non-empty.
     */
    public var array: [Float]
    public var offset: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * On/off lengths. Even in length and non-empty.
         */array: [Float], offset: Float) {
        self.array = array
        self.offset = offset
    }
}



extension Dash: Equatable, Hashable {
    public static func ==(lhs: Dash, rhs: Dash) -> Bool {
        if lhs.array != rhs.array {
            return false
        }
        if lhs.offset != rhs.offset {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(array)
        hasher.combine(offset)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDash: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Dash {
        return
            try Dash(
                array: FfiConverterSequenceFloat.read(from: &buf), 
                offset: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: Dash, into buf: inout [UInt8]) {
        FfiConverterSequenceFloat.write(value.array, into: &buf)
        FfiConverterFloat.write(value.offset, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDash_lift(_ buf: RustBuffer) throws -> Dash {
    return try FfiConverterTypeDash.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDash_lower(_ value: Dash) -> RustBuffer {
    return FfiConverterTypeDash.lower(value)
}


/**
 * The flattened picture.
 */
public struct DisplayList {
    /**
     * Canvas width in user units.
     */
    public var width: Float
    /**
     * Canvas height in user units.
     */
    public var height: Float
    /**
     * The operations, in paint order. Every `PushLayer` has a matching
     * `PopLayer` later in the list; they nest.
     */
    public var ops: [Op]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Canvas width in user units.
         */width: Float, 
        /**
         * Canvas height in user units.
         */height: Float, 
        /**
         * The operations, in paint order. Every `PushLayer` has a matching
         * `PopLayer` later in the list; they nest.
         */ops: [Op]) {
        self.width = width
        self.height = height
        self.ops = ops
    }
}



extension DisplayList: Equatable, Hashable {
    public static func ==(lhs: DisplayList, rhs: DisplayList) -> Bool {
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.ops != rhs.ops {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(ops)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDisplayList: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DisplayList {
        return
            try DisplayList(
                width: FfiConverterFloat.read(from: &buf), 
                height: FfiConverterFloat.read(from: &buf), 
                ops: FfiConverterSequenceTypeOp.read(from: &buf)
        )
    }

    public static func write(_ value: DisplayList, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
        FfiConverterSequenceTypeOp.write(value.ops, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDisplayList_lift(_ buf: RustBuffer) throws -> DisplayList {
    return try FfiConverterTypeDisplayList.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDisplayList_lower(_ value: DisplayList) -> RustBuffer {
    return FfiConverterTypeDisplayList.lower(value)
}


/**
 * Fill a path.
 */
public struct FillOp {
    public var path: Path
    /**
     * Local to canvas.
     */
    public var transform: Transform
    public var paint: Paint
    /**
     * `fill-opacity`, `0.0..=1.0`.
     */
    public var opacity: Float
    public var rule: FillRule
    /**
     * Whether edges should be anti-aliased.
     */
    public var antialias: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: Path, 
        /**
         * Local to canvas.
         */transform: Transform, paint: Paint, 
        /**
         * `fill-opacity`, `0.0..=1.0`.
         */opacity: Float, rule: FillRule, 
        /**
         * Whether edges should be anti-aliased.
         */antialias: Bool) {
        self.path = path
        self.transform = transform
        self.paint = paint
        self.opacity = opacity
        self.rule = rule
        self.antialias = antialias
    }
}



extension FillOp: Equatable, Hashable {
    public static func ==(lhs: FillOp, rhs: FillOp) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.paint != rhs.paint {
            return false
        }
        if lhs.opacity != rhs.opacity {
            return false
        }
        if lhs.rule != rhs.rule {
            return false
        }
        if lhs.antialias != rhs.antialias {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(transform)
        hasher.combine(paint)
        hasher.combine(opacity)
        hasher.combine(rule)
        hasher.combine(antialias)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFillOp: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FillOp {
        return
            try FillOp(
                path: FfiConverterTypePath.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                paint: FfiConverterTypePaint.read(from: &buf), 
                opacity: FfiConverterFloat.read(from: &buf), 
                rule: FfiConverterTypeFillRule.read(from: &buf), 
                antialias: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FillOp, into buf: inout [UInt8]) {
        FfiConverterTypePath.write(value.path, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterTypePaint.write(value.paint, into: &buf)
        FfiConverterFloat.write(value.opacity, into: &buf)
        FfiConverterTypeFillRule.write(value.rule, into: &buf)
        FfiConverterBool.write(value.antialias, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillOp_lift(_ buf: RustBuffer) throws -> FillOp {
    return try FfiConverterTypeFillOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillOp_lower(_ value: FillOp) -> RustBuffer {
    return FfiConverterTypeFillOp.lower(value)
}


/**
 * An encoded raster `<image>`.
 */
public struct ImageOp {
    /**
     * The file bytes, still encoded.
     */
    public var data: Data
    public var format: ImageFormat
    /**
     * Pixel width of the decoded image.
     */
    public var width: Float
    /**
     * Pixel height of the decoded image.
     */
    public var height: Float
    /**
     * Local to canvas, where local is the pixel rectangle `(0, 0, width, height)`.
     */
    public var transform: Transform
    /**
     * Whether to interpolate when scaling, rather than pick nearest pixels.
     */
    public var smooth: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The file bytes, still encoded.
         */data: Data, format: ImageFormat, 
        /**
         * Pixel width of the decoded image.
         */width: Float, 
        /**
         * Pixel height of the decoded image.
         */height: Float, 
        /**
         * Local to canvas, where local is the pixel rectangle `(0, 0, width, height)`.
         */transform: Transform, 
        /**
         * Whether to interpolate when scaling, rather than pick nearest pixels.
         */smooth: Bool) {
        self.data = data
        self.format = format
        self.width = width
        self.height = height
        self.transform = transform
        self.smooth = smooth
    }
}



extension ImageOp: Equatable, Hashable {
    public static func ==(lhs: ImageOp, rhs: ImageOp) -> Bool {
        if lhs.data != rhs.data {
            return false
        }
        if lhs.format != rhs.format {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.smooth != rhs.smooth {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(data)
        hasher.combine(format)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(transform)
        hasher.combine(smooth)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageOp: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageOp {
        return
            try ImageOp(
                data: FfiConverterData.read(from: &buf), 
                format: FfiConverterTypeImageFormat.read(from: &buf), 
                width: FfiConverterFloat.read(from: &buf), 
                height: FfiConverterFloat.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                smooth: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ImageOp, into buf: inout [UInt8]) {
        FfiConverterData.write(value.data, into: &buf)
        FfiConverterTypeImageFormat.write(value.format, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterBool.write(value.smooth, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageOp_lift(_ buf: RustBuffer) throws -> ImageOp {
    return try FfiConverterTypeImageOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageOp_lower(_ value: ImageOp) -> RustBuffer {
    return FfiConverterTypeImageOp.lower(value)
}


/**
 * A compositing layer.
 */
public struct Layer {
    /**
     * Group opacity, `0.0..=1.0`.
     */
    public var opacity: Float
    /**
     * How the layer composites onto what is beneath it.
     */
    public var blend: BlendMode
    /**
     * Clips to apply, intersected in order. Each is a union of shapes.
     */
    public var clips: [Clip]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Group opacity, `0.0..=1.0`.
         */opacity: Float, 
        /**
         * How the layer composites onto what is beneath it.
         */blend: BlendMode, 
        /**
         * Clips to apply, intersected in order. Each is a union of shapes.
         */clips: [Clip]) {
        self.opacity = opacity
        self.blend = blend
        self.clips = clips
    }
}



extension Layer: Equatable, Hashable {
    public static func ==(lhs: Layer, rhs: Layer) -> Bool {
        if lhs.opacity != rhs.opacity {
            return false
        }
        if lhs.blend != rhs.blend {
            return false
        }
        if lhs.clips != rhs.clips {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(opacity)
        hasher.combine(blend)
        hasher.combine(clips)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLayer: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Layer {
        return
            try Layer(
                opacity: FfiConverterFloat.read(from: &buf), 
                blend: FfiConverterTypeBlendMode.read(from: &buf), 
                clips: FfiConverterSequenceTypeClip.read(from: &buf)
        )
    }

    public static func write(_ value: Layer, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.opacity, into: &buf)
        FfiConverterTypeBlendMode.write(value.blend, into: &buf)
        FfiConverterSequenceTypeClip.write(value.clips, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayer_lift(_ buf: RustBuffer) throws -> Layer {
    return try FfiConverterTypeLayer.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLayer_lower(_ value: Layer) -> RustBuffer {
    return FfiConverterTypeLayer.lower(value)
}


/**
 * A linear gradient in the path's local space, after `transform`.
 */
public struct LinearGradient {
    public var x1: Float
    public var y1: Float
    public var x2: Float
    public var y2: Float
    public var transform: Transform
    /**
     * At least two, offsets ascending in `0.0..=1.0`.
     */
    public var stops: [Stop]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x1: Float, y1: Float, x2: Float, y2: Float, transform: Transform, 
        /**
         * At least two, offsets ascending in `0.0..=1.0`.
         */stops: [Stop]) {
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2
        self.y2 = y2
        self.transform = transform
        self.stops = stops
    }
}



extension LinearGradient: Equatable, Hashable {
    public static func ==(lhs: LinearGradient, rhs: LinearGradient) -> Bool {
        if lhs.x1 != rhs.x1 {
            return false
        }
        if lhs.y1 != rhs.y1 {
            return false
        }
        if lhs.x2 != rhs.x2 {
            return false
        }
        if lhs.y2 != rhs.y2 {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.stops != rhs.stops {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x1)
        hasher.combine(y1)
        hasher.combine(x2)
        hasher.combine(y2)
        hasher.combine(transform)
        hasher.combine(stops)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLinearGradient: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LinearGradient {
        return
            try LinearGradient(
                x1: FfiConverterFloat.read(from: &buf), 
                y1: FfiConverterFloat.read(from: &buf), 
                x2: FfiConverterFloat.read(from: &buf), 
                y2: FfiConverterFloat.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                stops: FfiConverterSequenceTypeStop.read(from: &buf)
        )
    }

    public static func write(_ value: LinearGradient, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.x1, into: &buf)
        FfiConverterFloat.write(value.y1, into: &buf)
        FfiConverterFloat.write(value.x2, into: &buf)
        FfiConverterFloat.write(value.y2, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterSequenceTypeStop.write(value.stops, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinearGradient_lift(_ buf: RustBuffer) throws -> LinearGradient {
    return try FfiConverterTypeLinearGradient.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLinearGradient_lower(_ value: LinearGradient) -> RustBuffer {
    return FfiConverterTypeLinearGradient.lower(value)
}


/**
 * How to parse. `Default` is what the SVG spec calls for, with system fonts.
 */
public struct ParseOptions {
    /**
     * Load the system's fonts so `<text>` in a face the document doesn't embed
     * still lays out. Loading is a directory walk done once per process and
     * shared by every document after; off, text in an unknown family falls
     * back to nothing and is dropped, which is what a sandboxed host with no
     * font access wants.
     */
    public var loadSystemFonts: Bool
    /**
     * The family for text that names none. usvg's default is Times New Roman.
     */
    public var fontFamily: String
    /**
     * The size for text that sets none, in user units.
     */
    public var fontSize: Float
    /**
     * Dots per inch, for `in`/`cm`/`mm` lengths. 96 is CSS's.
     */
    public var dpi: Float
    /**
     * Directory that relative `href`s (in `<image>`) resolve against; `None`
     * leaves them unresolved.
     */
    public var resourcesDir: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Load the system's fonts so `<text>` in a face the document doesn't embed
         * still lays out. Loading is a directory walk done once per process and
         * shared by every document after; off, text in an unknown family falls
         * back to nothing and is dropped, which is what a sandboxed host with no
         * font access wants.
         */loadSystemFonts: Bool = true, 
        /**
         * The family for text that names none. usvg's default is Times New Roman.
         */fontFamily: String = "Times New Roman", 
        /**
         * The size for text that sets none, in user units.
         */fontSize: Float = Float(12.0), 
        /**
         * Dots per inch, for `in`/`cm`/`mm` lengths. 96 is CSS's.
         */dpi: Float = Float(96.0), 
        /**
         * Directory that relative `href`s (in `<image>`) resolve against; `None`
         * leaves them unresolved.
         */resourcesDir: String? = nil) {
        self.loadSystemFonts = loadSystemFonts
        self.fontFamily = fontFamily
        self.fontSize = fontSize
        self.dpi = dpi
        self.resourcesDir = resourcesDir
    }
}



extension ParseOptions: Equatable, Hashable {
    public static func ==(lhs: ParseOptions, rhs: ParseOptions) -> Bool {
        if lhs.loadSystemFonts != rhs.loadSystemFonts {
            return false
        }
        if lhs.fontFamily != rhs.fontFamily {
            return false
        }
        if lhs.fontSize != rhs.fontSize {
            return false
        }
        if lhs.dpi != rhs.dpi {
            return false
        }
        if lhs.resourcesDir != rhs.resourcesDir {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(loadSystemFonts)
        hasher.combine(fontFamily)
        hasher.combine(fontSize)
        hasher.combine(dpi)
        hasher.combine(resourcesDir)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeParseOptions: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ParseOptions {
        return
            try ParseOptions(
                loadSystemFonts: FfiConverterBool.read(from: &buf), 
                fontFamily: FfiConverterString.read(from: &buf), 
                fontSize: FfiConverterFloat.read(from: &buf), 
                dpi: FfiConverterFloat.read(from: &buf), 
                resourcesDir: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: ParseOptions, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.loadSystemFonts, into: &buf)
        FfiConverterString.write(value.fontFamily, into: &buf)
        FfiConverterFloat.write(value.fontSize, into: &buf)
        FfiConverterFloat.write(value.dpi, into: &buf)
        FfiConverterOptionString.write(value.resourcesDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParseOptions_lift(_ buf: RustBuffer) throws -> ParseOptions {
    return try FfiConverterTypeParseOptions.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeParseOptions_lower(_ value: ParseOptions) -> RustBuffer {
    return FfiConverterTypeParseOptions.lower(value)
}


/**
 * A path as verbs, in its local space.
 */
public struct Path {
    public var verbs: [PathVerb]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(verbs: [PathVerb]) {
        self.verbs = verbs
    }
}



extension Path: Equatable, Hashable {
    public static func ==(lhs: Path, rhs: Path) -> Bool {
        if lhs.verbs != rhs.verbs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(verbs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePath: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Path {
        return
            try Path(
                verbs: FfiConverterSequenceTypePathVerb.read(from: &buf)
        )
    }

    public static func write(_ value: Path, into buf: inout [UInt8]) {
        FfiConverterSequenceTypePathVerb.write(value.verbs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePath_lift(_ buf: RustBuffer) throws -> Path {
    return try FfiConverterTypePath.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePath_lower(_ value: Path) -> RustBuffer {
    return FfiConverterTypePath.lower(value)
}


/**
 * A radial gradient: from the focal point `(fx, fy)` at radius 0 to the
 * circle centred `(cx, cy)` at radius `r`.
 */
public struct RadialGradient {
    public var cx: Float
    public var cy: Float
    public var r: Float
    public var fx: Float
    public var fy: Float
    public var transform: Transform
    /**
     * At least two, offsets ascending in `0.0..=1.0`.
     */
    public var stops: [Stop]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cx: Float, cy: Float, r: Float, fx: Float, fy: Float, transform: Transform, 
        /**
         * At least two, offsets ascending in `0.0..=1.0`.
         */stops: [Stop]) {
        self.cx = cx
        self.cy = cy
        self.r = r
        self.fx = fx
        self.fy = fy
        self.transform = transform
        self.stops = stops
    }
}



extension RadialGradient: Equatable, Hashable {
    public static func ==(lhs: RadialGradient, rhs: RadialGradient) -> Bool {
        if lhs.cx != rhs.cx {
            return false
        }
        if lhs.cy != rhs.cy {
            return false
        }
        if lhs.r != rhs.r {
            return false
        }
        if lhs.fx != rhs.fx {
            return false
        }
        if lhs.fy != rhs.fy {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.stops != rhs.stops {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(cx)
        hasher.combine(cy)
        hasher.combine(r)
        hasher.combine(fx)
        hasher.combine(fy)
        hasher.combine(transform)
        hasher.combine(stops)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRadialGradient: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RadialGradient {
        return
            try RadialGradient(
                cx: FfiConverterFloat.read(from: &buf), 
                cy: FfiConverterFloat.read(from: &buf), 
                r: FfiConverterFloat.read(from: &buf), 
                fx: FfiConverterFloat.read(from: &buf), 
                fy: FfiConverterFloat.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                stops: FfiConverterSequenceTypeStop.read(from: &buf)
        )
    }

    public static func write(_ value: RadialGradient, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.cx, into: &buf)
        FfiConverterFloat.write(value.cy, into: &buf)
        FfiConverterFloat.write(value.r, into: &buf)
        FfiConverterFloat.write(value.fx, into: &buf)
        FfiConverterFloat.write(value.fy, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterSequenceTypeStop.write(value.stops, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRadialGradient_lift(_ buf: RustBuffer) throws -> RadialGradient {
    return try FfiConverterTypeRadialGradient.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRadialGradient_lower(_ value: RadialGradient) -> RustBuffer {
    return FfiConverterTypeRadialGradient.lower(value)
}


/**
 * Pixels for a subtree that is not expressed as vectors.
 */
public struct RasterOp {
    /**
     * Premultiplied RGBA, 8 bits per channel, row-major, `width * height * 4`.
     */
    public var rgba: Data
    public var width: UInt32
    public var height: UInt32
    /**
     * The canvas rectangle the pixels cover, in user units.
     */
    public var rect: Rect

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Premultiplied RGBA, 8 bits per channel, row-major, `width * height * 4`.
         */rgba: Data, width: UInt32, height: UInt32, 
        /**
         * The canvas rectangle the pixels cover, in user units.
         */rect: Rect) {
        self.rgba = rgba
        self.width = width
        self.height = height
        self.rect = rect
    }
}



extension RasterOp: Equatable, Hashable {
    public static func ==(lhs: RasterOp, rhs: RasterOp) -> Bool {
        if lhs.rgba != rhs.rgba {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        if lhs.rect != rhs.rect {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rgba)
        hasher.combine(width)
        hasher.combine(height)
        hasher.combine(rect)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRasterOp: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RasterOp {
        return
            try RasterOp(
                rgba: FfiConverterData.read(from: &buf), 
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf), 
                rect: FfiConverterTypeRect.read(from: &buf)
        )
    }

    public static func write(_ value: RasterOp, into buf: inout [UInt8]) {
        FfiConverterData.write(value.rgba, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterTypeRect.write(value.rect, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRasterOp_lift(_ buf: RustBuffer) throws -> RasterOp {
    return try FfiConverterTypeRasterOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRasterOp_lower(_ value: RasterOp) -> RustBuffer {
    return FfiConverterTypeRasterOp.lower(value)
}


/**
 * An axis-aligned rectangle in canvas units.
 */
public struct Rect {
    public var x: Float
    public var y: Float
    public var width: Float
    public var height: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Float, y: Float, width: Float, height: Float) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }
}



extension Rect: Equatable, Hashable {
    public static func ==(lhs: Rect, rhs: Rect) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(width)
        hasher.combine(height)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRect: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Rect {
        return
            try Rect(
                x: FfiConverterFloat.read(from: &buf), 
                y: FfiConverterFloat.read(from: &buf), 
                width: FfiConverterFloat.read(from: &buf), 
                height: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: Rect, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.x, into: &buf)
        FfiConverterFloat.write(value.y, into: &buf)
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterFloat.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lift(_ buf: RustBuffer) throws -> Rect {
    return try FfiConverterTypeRect.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lower(_ value: Rect) -> RustBuffer {
    return FfiConverterTypeRect.lower(value)
}


/**
 * One gradient stop.
 */
public struct Stop {
    /**
     * Position along the gradient, `0.0..=1.0`.
     */
    public var offset: Float
    public var color: Color
    /**
     * `stop-opacity`, already multiplied by the op's opacity.
     */
    public var opacity: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Position along the gradient, `0.0..=1.0`.
         */offset: Float, color: Color, 
        /**
         * `stop-opacity`, already multiplied by the op's opacity.
         */opacity: Float) {
        self.offset = offset
        self.color = color
        self.opacity = opacity
    }
}



extension Stop: Equatable, Hashable {
    public static func ==(lhs: Stop, rhs: Stop) -> Bool {
        if lhs.offset != rhs.offset {
            return false
        }
        if lhs.color != rhs.color {
            return false
        }
        if lhs.opacity != rhs.opacity {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(offset)
        hasher.combine(color)
        hasher.combine(opacity)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStop: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Stop {
        return
            try Stop(
                offset: FfiConverterFloat.read(from: &buf), 
                color: FfiConverterTypeColor.read(from: &buf), 
                opacity: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: Stop, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.offset, into: &buf)
        FfiConverterTypeColor.write(value.color, into: &buf)
        FfiConverterFloat.write(value.opacity, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStop_lift(_ buf: RustBuffer) throws -> Stop {
    return try FfiConverterTypeStop.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStop_lower(_ value: Stop) -> RustBuffer {
    return FfiConverterTypeStop.lower(value)
}


/**
 * Stroke a path.
 */
public struct StrokeOp {
    public var path: Path
    /**
     * Local to canvas. Apply before stroking, so the width is in local units.
     */
    public var transform: Transform
    public var paint: Paint
    /**
     * `stroke-opacity`, `0.0..=1.0`.
     */
    public var opacity: Float
    public var stroke: StrokeStyle
    /**
     * Whether edges should be anti-aliased.
     */
    public var antialias: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: Path, 
        /**
         * Local to canvas. Apply before stroking, so the width is in local units.
         */transform: Transform, paint: Paint, 
        /**
         * `stroke-opacity`, `0.0..=1.0`.
         */opacity: Float, stroke: StrokeStyle, 
        /**
         * Whether edges should be anti-aliased.
         */antialias: Bool) {
        self.path = path
        self.transform = transform
        self.paint = paint
        self.opacity = opacity
        self.stroke = stroke
        self.antialias = antialias
    }
}



extension StrokeOp: Equatable, Hashable {
    public static func ==(lhs: StrokeOp, rhs: StrokeOp) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.transform != rhs.transform {
            return false
        }
        if lhs.paint != rhs.paint {
            return false
        }
        if lhs.opacity != rhs.opacity {
            return false
        }
        if lhs.stroke != rhs.stroke {
            return false
        }
        if lhs.antialias != rhs.antialias {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(transform)
        hasher.combine(paint)
        hasher.combine(opacity)
        hasher.combine(stroke)
        hasher.combine(antialias)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStrokeOp: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StrokeOp {
        return
            try StrokeOp(
                path: FfiConverterTypePath.read(from: &buf), 
                transform: FfiConverterTypeTransform.read(from: &buf), 
                paint: FfiConverterTypePaint.read(from: &buf), 
                opacity: FfiConverterFloat.read(from: &buf), 
                stroke: FfiConverterTypeStrokeStyle.read(from: &buf), 
                antialias: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: StrokeOp, into buf: inout [UInt8]) {
        FfiConverterTypePath.write(value.path, into: &buf)
        FfiConverterTypeTransform.write(value.transform, into: &buf)
        FfiConverterTypePaint.write(value.paint, into: &buf)
        FfiConverterFloat.write(value.opacity, into: &buf)
        FfiConverterTypeStrokeStyle.write(value.stroke, into: &buf)
        FfiConverterBool.write(value.antialias, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStrokeOp_lift(_ buf: RustBuffer) throws -> StrokeOp {
    return try FfiConverterTypeStrokeOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStrokeOp_lower(_ value: StrokeOp) -> RustBuffer {
    return FfiConverterTypeStrokeOp.lower(value)
}


/**
 * The pen for a stroke, in the path's local units.
 */
public struct StrokeStyle {
    public var width: Float
    public var cap: LineCap
    public var join: LineJoin
    public var miterLimit: Float
    public var dash: Dash?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: Float, cap: LineCap, join: LineJoin, miterLimit: Float, dash: Dash?) {
        self.width = width
        self.cap = cap
        self.join = join
        self.miterLimit = miterLimit
        self.dash = dash
    }
}



extension StrokeStyle: Equatable, Hashable {
    public static func ==(lhs: StrokeStyle, rhs: StrokeStyle) -> Bool {
        if lhs.width != rhs.width {
            return false
        }
        if lhs.cap != rhs.cap {
            return false
        }
        if lhs.join != rhs.join {
            return false
        }
        if lhs.miterLimit != rhs.miterLimit {
            return false
        }
        if lhs.dash != rhs.dash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(width)
        hasher.combine(cap)
        hasher.combine(join)
        hasher.combine(miterLimit)
        hasher.combine(dash)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStrokeStyle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StrokeStyle {
        return
            try StrokeStyle(
                width: FfiConverterFloat.read(from: &buf), 
                cap: FfiConverterTypeLineCap.read(from: &buf), 
                join: FfiConverterTypeLineJoin.read(from: &buf), 
                miterLimit: FfiConverterFloat.read(from: &buf), 
                dash: FfiConverterOptionTypeDash.read(from: &buf)
        )
    }

    public static func write(_ value: StrokeStyle, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.width, into: &buf)
        FfiConverterTypeLineCap.write(value.cap, into: &buf)
        FfiConverterTypeLineJoin.write(value.join, into: &buf)
        FfiConverterFloat.write(value.miterLimit, into: &buf)
        FfiConverterOptionTypeDash.write(value.dash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStrokeStyle_lift(_ buf: RustBuffer) throws -> StrokeStyle {
    return try FfiConverterTypeStrokeStyle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStrokeStyle_lower(_ value: StrokeStyle) -> RustBuffer {
    return FfiConverterTypeStrokeStyle.lower(value)
}


/**
 * A 2D affine transform: `x' = sx·x + kx·y + tx`, `y' = ky·x + sy·y + ty`.
 * `CGAffineTransform(a: sx, b: ky, c: kx, d: sy, tx, ty)` is the same matrix.
 */
public struct Transform {
    public var sx: Float
    public var kx: Float
    public var ky: Float
    public var sy: Float
    public var tx: Float
    public var ty: Float

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sx: Float, kx: Float, ky: Float, sy: Float, tx: Float, ty: Float) {
        self.sx = sx
        self.kx = kx
        self.ky = ky
        self.sy = sy
        self.tx = tx
        self.ty = ty
    }
}



extension Transform: Equatable, Hashable {
    public static func ==(lhs: Transform, rhs: Transform) -> Bool {
        if lhs.sx != rhs.sx {
            return false
        }
        if lhs.kx != rhs.kx {
            return false
        }
        if lhs.ky != rhs.ky {
            return false
        }
        if lhs.sy != rhs.sy {
            return false
        }
        if lhs.tx != rhs.tx {
            return false
        }
        if lhs.ty != rhs.ty {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(sx)
        hasher.combine(kx)
        hasher.combine(ky)
        hasher.combine(sy)
        hasher.combine(tx)
        hasher.combine(ty)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTransform: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Transform {
        return
            try Transform(
                sx: FfiConverterFloat.read(from: &buf), 
                kx: FfiConverterFloat.read(from: &buf), 
                ky: FfiConverterFloat.read(from: &buf), 
                sy: FfiConverterFloat.read(from: &buf), 
                tx: FfiConverterFloat.read(from: &buf), 
                ty: FfiConverterFloat.read(from: &buf)
        )
    }

    public static func write(_ value: Transform, into buf: inout [UInt8]) {
        FfiConverterFloat.write(value.sx, into: &buf)
        FfiConverterFloat.write(value.kx, into: &buf)
        FfiConverterFloat.write(value.ky, into: &buf)
        FfiConverterFloat.write(value.sy, into: &buf)
        FfiConverterFloat.write(value.tx, into: &buf)
        FfiConverterFloat.write(value.ty, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransform_lift(_ buf: RustBuffer) throws -> Transform {
    return try FfiConverterTypeTransform.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTransform_lower(_ value: Transform) -> RustBuffer {
    return FfiConverterTypeTransform.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * `mix-blend-mode`, the sixteen CSS compositing modes.
 */

public enum BlendMode {
    
    case normal
    case multiply
    case screen
    case overlay
    case darken
    case lighten
    case colorDodge
    case colorBurn
    case hardLight
    case softLight
    case difference
    case exclusion
    case hue
    case saturation
    case color
    case luminosity
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBlendMode: FfiConverterRustBuffer {
    typealias SwiftType = BlendMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BlendMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .normal
        
        case 2: return .multiply
        
        case 3: return .screen
        
        case 4: return .overlay
        
        case 5: return .darken
        
        case 6: return .lighten
        
        case 7: return .colorDodge
        
        case 8: return .colorBurn
        
        case 9: return .hardLight
        
        case 10: return .softLight
        
        case 11: return .difference
        
        case 12: return .exclusion
        
        case 13: return .hue
        
        case 14: return .saturation
        
        case 15: return .color
        
        case 16: return .luminosity
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BlendMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .normal:
            writeInt(&buf, Int32(1))
        
        
        case .multiply:
            writeInt(&buf, Int32(2))
        
        
        case .screen:
            writeInt(&buf, Int32(3))
        
        
        case .overlay:
            writeInt(&buf, Int32(4))
        
        
        case .darken:
            writeInt(&buf, Int32(5))
        
        
        case .lighten:
            writeInt(&buf, Int32(6))
        
        
        case .colorDodge:
            writeInt(&buf, Int32(7))
        
        
        case .colorBurn:
            writeInt(&buf, Int32(8))
        
        
        case .hardLight:
            writeInt(&buf, Int32(9))
        
        
        case .softLight:
            writeInt(&buf, Int32(10))
        
        
        case .difference:
            writeInt(&buf, Int32(11))
        
        
        case .exclusion:
            writeInt(&buf, Int32(12))
        
        
        case .hue:
            writeInt(&buf, Int32(13))
        
        
        case .saturation:
            writeInt(&buf, Int32(14))
        
        
        case .color:
            writeInt(&buf, Int32(15))
        
        
        case .luminosity:
            writeInt(&buf, Int32(16))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlendMode_lift(_ buf: RustBuffer) throws -> BlendMode {
    return try FfiConverterTypeBlendMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBlendMode_lower(_ value: BlendMode) -> RustBuffer {
    return FfiConverterTypeBlendMode.lower(value)
}



extension BlendMode: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How a path's interior is decided.
 */

public enum FillRule {
    
    case nonZero
    case evenOdd
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFillRule: FfiConverterRustBuffer {
    typealias SwiftType = FillRule

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FillRule {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .nonZero
        
        case 2: return .evenOdd
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FillRule, into buf: inout [UInt8]) {
        switch value {
        
        
        case .nonZero:
            writeInt(&buf, Int32(1))
        
        
        case .evenOdd:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillRule_lift(_ buf: RustBuffer) throws -> FillRule {
    return try FfiConverterTypeFillRule.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFillRule_lower(_ value: FillRule) -> RustBuffer {
    return FfiConverterTypeFillRule.lower(value)
}



extension FillRule: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * The encoding of an image's bytes.
 */

public enum ImageFormat {
    
    case png
    case jpeg
    case gif
    case webp
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeImageFormat: FfiConverterRustBuffer {
    typealias SwiftType = ImageFormat

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ImageFormat {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .png
        
        case 2: return .jpeg
        
        case 3: return .gif
        
        case 4: return .webp
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ImageFormat, into buf: inout [UInt8]) {
        switch value {
        
        
        case .png:
            writeInt(&buf, Int32(1))
        
        
        case .jpeg:
            writeInt(&buf, Int32(2))
        
        
        case .gif:
            writeInt(&buf, Int32(3))
        
        
        case .webp:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageFormat_lift(_ buf: RustBuffer) throws -> ImageFormat {
    return try FfiConverterTypeImageFormat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeImageFormat_lower(_ value: ImageFormat) -> RustBuffer {
    return FfiConverterTypeImageFormat.lower(value)
}



extension ImageFormat: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * `stroke-linecap`.
 */

public enum LineCap {
    
    case butt
    case round
    case square
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLineCap: FfiConverterRustBuffer {
    typealias SwiftType = LineCap

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LineCap {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .butt
        
        case 2: return .round
        
        case 3: return .square
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LineCap, into buf: inout [UInt8]) {
        switch value {
        
        
        case .butt:
            writeInt(&buf, Int32(1))
        
        
        case .round:
            writeInt(&buf, Int32(2))
        
        
        case .square:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLineCap_lift(_ buf: RustBuffer) throws -> LineCap {
    return try FfiConverterTypeLineCap.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLineCap_lower(_ value: LineCap) -> RustBuffer {
    return FfiConverterTypeLineCap.lower(value)
}



extension LineCap: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * `stroke-linejoin`. A backend without `MiterClip` falls back to `Miter`.
 */

public enum LineJoin {
    
    case miter
    case miterClip
    case round
    case bevel
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLineJoin: FfiConverterRustBuffer {
    typealias SwiftType = LineJoin

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LineJoin {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .miter
        
        case 2: return .miterClip
        
        case 3: return .round
        
        case 4: return .bevel
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LineJoin, into buf: inout [UInt8]) {
        switch value {
        
        
        case .miter:
            writeInt(&buf, Int32(1))
        
        
        case .miterClip:
            writeInt(&buf, Int32(2))
        
        
        case .round:
            writeInt(&buf, Int32(3))
        
        
        case .bevel:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLineJoin_lift(_ buf: RustBuffer) throws -> LineJoin {
    return try FfiConverterTypeLineJoin.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLineJoin_lower(_ value: LineJoin) -> RustBuffer {
    return FfiConverterTypeLineJoin.lower(value)
}



extension LineJoin: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * One drawing operation.
 */

public enum Op {
    
    /**
     * Begin a compositing layer, ended by the matching `PopLayer`.
     */
    case pushLayer(layer: Layer
    )
    /**
     * End the innermost layer.
     */
    case popLayer
    /**
     * Fill a path.
     */
    case fill(op: FillOp
    )
    /**
     * Stroke a path.
     */
    case stroke(op: StrokeOp
    )
    /**
     * Draw an encoded raster image.
     */
    case image(op: ImageOp
    )
    /**
     * Draw pixels resvg produced for a subtree with no vector form here.
     */
    case raster(op: RasterOp
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOp: FfiConverterRustBuffer {
    typealias SwiftType = Op

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Op {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pushLayer(layer: try FfiConverterTypeLayer.read(from: &buf)
        )
        
        case 2: return .popLayer
        
        case 3: return .fill(op: try FfiConverterTypeFillOp.read(from: &buf)
        )
        
        case 4: return .stroke(op: try FfiConverterTypeStrokeOp.read(from: &buf)
        )
        
        case 5: return .image(op: try FfiConverterTypeImageOp.read(from: &buf)
        )
        
        case 6: return .raster(op: try FfiConverterTypeRasterOp.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Op, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .pushLayer(layer):
            writeInt(&buf, Int32(1))
            FfiConverterTypeLayer.write(layer, into: &buf)
            
        
        case .popLayer:
            writeInt(&buf, Int32(2))
        
        
        case let .fill(op):
            writeInt(&buf, Int32(3))
            FfiConverterTypeFillOp.write(op, into: &buf)
            
        
        case let .stroke(op):
            writeInt(&buf, Int32(4))
            FfiConverterTypeStrokeOp.write(op, into: &buf)
            
        
        case let .image(op):
            writeInt(&buf, Int32(5))
            FfiConverterTypeImageOp.write(op, into: &buf)
            
        
        case let .raster(op):
            writeInt(&buf, Int32(6))
            FfiConverterTypeRasterOp.write(op, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOp_lift(_ buf: RustBuffer) throws -> Op {
    return try FfiConverterTypeOp.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOp_lower(_ value: Op) -> RustBuffer {
    return FfiConverterTypeOp.lower(value)
}



extension Op: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * What a fill or stroke is painted with.
 */

public enum Paint {
    
    case solid(color: Color
    )
    case linear(gradient: LinearGradient
    )
    case radial(gradient: RadialGradient
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePaint: FfiConverterRustBuffer {
    typealias SwiftType = Paint

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Paint {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .solid(color: try FfiConverterTypeColor.read(from: &buf)
        )
        
        case 2: return .linear(gradient: try FfiConverterTypeLinearGradient.read(from: &buf)
        )
        
        case 3: return .radial(gradient: try FfiConverterTypeRadialGradient.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Paint, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .solid(color):
            writeInt(&buf, Int32(1))
            FfiConverterTypeColor.write(color, into: &buf)
            
        
        case let .linear(gradient):
            writeInt(&buf, Int32(2))
            FfiConverterTypeLinearGradient.write(gradient, into: &buf)
            
        
        case let .radial(gradient):
            writeInt(&buf, Int32(3))
            FfiConverterTypeRadialGradient.write(gradient, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaint_lift(_ buf: RustBuffer) throws -> Paint {
    return try FfiConverterTypePaint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaint_lower(_ value: Paint) -> RustBuffer {
    return FfiConverterTypePaint.lower(value)
}



extension Paint: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * One path verb. Coordinates are absolute in the path's local space.
 */

public enum PathVerb {
    
    case moveTo(x: Float, y: Float
    )
    case lineTo(x: Float, y: Float
    )
    case quadTo(x1: Float, y1: Float, x: Float, y: Float
    )
    case cubicTo(x1: Float, y1: Float, x2: Float, y2: Float, x: Float, y: Float
    )
    case close
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePathVerb: FfiConverterRustBuffer {
    typealias SwiftType = PathVerb

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PathVerb {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .moveTo(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf)
        )
        
        case 2: return .lineTo(x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf)
        )
        
        case 3: return .quadTo(x1: try FfiConverterFloat.read(from: &buf), y1: try FfiConverterFloat.read(from: &buf), x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf)
        )
        
        case 4: return .cubicTo(x1: try FfiConverterFloat.read(from: &buf), y1: try FfiConverterFloat.read(from: &buf), x2: try FfiConverterFloat.read(from: &buf), y2: try FfiConverterFloat.read(from: &buf), x: try FfiConverterFloat.read(from: &buf), y: try FfiConverterFloat.read(from: &buf)
        )
        
        case 5: return .close
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PathVerb, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .moveTo(x,y):
            writeInt(&buf, Int32(1))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            
        
        case let .lineTo(x,y):
            writeInt(&buf, Int32(2))
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            
        
        case let .quadTo(x1,y1,x,y):
            writeInt(&buf, Int32(3))
            FfiConverterFloat.write(x1, into: &buf)
            FfiConverterFloat.write(y1, into: &buf)
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            
        
        case let .cubicTo(x1,y1,x2,y2,x,y):
            writeInt(&buf, Int32(4))
            FfiConverterFloat.write(x1, into: &buf)
            FfiConverterFloat.write(y1, into: &buf)
            FfiConverterFloat.write(x2, into: &buf)
            FfiConverterFloat.write(y2, into: &buf)
            FfiConverterFloat.write(x, into: &buf)
            FfiConverterFloat.write(y, into: &buf)
            
        
        case .close:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePathVerb_lift(_ buf: RustBuffer) throws -> PathVerb {
    return try FfiConverterTypePathVerb.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePathVerb_lower(_ value: PathVerb) -> RustBuffer {
    return FfiConverterTypePathVerb.lower(value)
}



extension PathVerb: Equatable, Hashable {}




/**
 * Why [`SvgDocument::new`] refused the bytes.
 */
public enum SvgError {

    
    
    /**
     * usvg could not parse the document; `message` is its reason.
     */
    case Parse(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSvgError: FfiConverterRustBuffer {
    typealias SwiftType = SvgError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SvgError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Parse(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SvgError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Parse(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension SvgError: Equatable, Hashable {}

extension SvgError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDash: FfiConverterRustBuffer {
    typealias SwiftType = Dash?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDash.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDash.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeClip: FfiConverterRustBuffer {
    typealias SwiftType = [Clip]

    public static func write(_ value: [Clip], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeClip.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Clip] {
        let len: Int32 = try readInt(&buf)
        var seq = [Clip]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeClip.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeClipShape: FfiConverterRustBuffer {
    typealias SwiftType = [ClipShape]

    public static func write(_ value: [ClipShape], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeClipShape.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ClipShape] {
        let len: Int32 = try readInt(&buf)
        var seq = [ClipShape]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeClipShape.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStop: FfiConverterRustBuffer {
    typealias SwiftType = [Stop]

    public static func write(_ value: [Stop], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStop.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Stop] {
        let len: Int32 = try readInt(&buf)
        var seq = [Stop]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStop.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOp: FfiConverterRustBuffer {
    typealias SwiftType = [Op]

    public static func write(_ value: [Op], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOp.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Op] {
        let len: Int32 = try readInt(&buf)
        var seq = [Op]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOp.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePathVerb: FfiConverterRustBuffer {
    typealias SwiftType = [PathVerb]

    public static func write(_ value: [PathVerb], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePathVerb.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PathVerb] {
        let len: Int32 = try readInt(&buf)
        var seq = [PathVerb]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePathVerb.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_resvg_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_resvg_swift_checksum_method_svgdocument_display_list() != 3139) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resvg_swift_checksum_method_svgdocument_has_text() != 9471) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resvg_swift_checksum_method_svgdocument_height() != 23344) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resvg_swift_checksum_method_svgdocument_width() != 6978) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_resvg_swift_checksum_constructor_svgdocument_new() != 8515) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all